label define ilabel 1 `"BN.CAB.XOKA.GD.ZS"', modify
label define ilabel 2 `"NE.CON.GOVT.ZS"', modify
label define ilabel 3 `"NE.CON.PETC.ZS"', modify
label define ilabel 4 `"NE.EXP.GNFS.ZS"', modify
label define ilabel 5 `"NE.GDI.TOTL.ZS"', modify
label define ilabel 6 `"NE.IMP.GNFS.ZS"', modify
label define ilabel 7 `"NY.GDP.PCAP.KN"', modify
label define ilabel 8 `"NY.GDP.PCAP.PP.KD"', modify
label define ilabel 9 `"PX.REX.REER"', modify
label define ilabel 10 `"SP.POP.TOTL"', modify
